from app.solve import router as solve
from app.auth import router as auth
from app.health import router as health
from app.resources import router as resources
from app.system import router as system
from app.workers import router as workers
from app.steel import router as steel
from app.chat import router as chat
from app.docs import router as docs
from app.pentest import router as pentest
from app.secrets import router as secrets
